<?php
require_once __DIR__ . '/config.php';
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <?php
    // Meta tags will be generated by individual pages
    if (isset($pageTitle)) {
        echo "<title>{$pageTitle} | " . SITE_NAME . "</title>\n";
    }
    ?>

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="/assets/images/favicon.png">

   

    <!-- Tailwind CSS CDN -->
    <script src="https://cdn.tailwindcss.com"></script>
 <!-- Tailwind CSS Configuration -->
    <script>
        tailwind.config = {
            darkMode: 'class',
        }
    </script>
    <!-- Custom CSS -->
    <link rel="stylesheet" href="/assets/css/style.css">

    <!-- PWA Manifest -->
    <link rel="manifest" href="/news-site/manifest.json">
    <meta name="theme-color" content="#3B82F6">

    <!-- Apple Touch Icon -->
    <link rel="apple-touch-icon" href="/assets/images/icons/icon-192x192.png">
</head>

<body class="bg-gray-50 dark:bg-gray-900">
    <!-- Header -->
    <header class="bg-white dark:bg-gray-900 shadow-md sticky top-0 z-50 transition-colors duration-200">
        <div class="container mx-auto px-4 py-4">
            <div class="flex items-center justify-between">
                <!-- Logo -->
                <a href="/" class="flex items-center gap-3">
                    <div class="w-10 h-10 overflow-hidden rounded-lg flex items-center justify-center">
                        <img src="https://gi1superverse.com/assets/logo.jpg" alt="Logo"
                            class="w-full h-full object-cover">
                    </div>
                    <span class="text-2xl font-bold text-gray-900 dark:text-white">
                        <?= SITE_NAME ?>
                    </span>
                </a>

                <!-- Navigation -->
                <nav class="hidden md:flex items-center gap-6">
                    <a href="/"
                        class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
                        Home
                    </a>
                    <a href="/news"
                        class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
                        All News
                    </a>
                    <a href="/category/technology"
                        class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
                        Technology
                    </a>
                    <a href="/category/business"
                        class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
                        Business
                    </a>
                </nav>

                <!-- Dark Mode Toggle -->
                <button id="theme-toggle" onclick="toggleDarkMode()"
                    class="p-2 rounded-lg bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 hover:bg-gray-200 dark:hover:bg-gray-600 transition-all duration-200"
                    title="Toggle Dark Mode">
                    <!-- Sun Icon (visible in dark mode) -->
                    <svg id="theme-toggle-light-icon" class="hidden dark:block w-5 h-5" fill="currentColor"
                        viewBox="0 0 20 20">
                        <path
                            d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z"
                            fill-rule="evenodd" clip-rule="evenodd"></path>
                    </svg>
                    <!-- Moon Icon (visible in light mode) -->
                    <svg id="theme-toggle-dark-icon" class="block dark:hidden w-5 h-5" fill="currentColor"
                        viewBox="0 0 20 20">
                        <path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path>
                    </svg>
                </button>

                <!-- Mobile Menu Button -->
                <button id="mobile-menu-btn" class="md:hidden text-gray-700 dark:text-gray-300">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M4 6h16M4 12h16M4 18h16"></path>
                    </svg>
                </button>
            </div>

            <!-- Mobile Menu -->
            <div id="mobile-menu" class="hidden md:hidden mt-4 pb-4">
                <nav class="flex flex-col gap-3">
                    <a href="/"
                        class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
                        Home
                    </a>
                    <a href="/news"
                        class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
                        All News
                    </a>
                    <a href="/category/technology"
                        class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
                        Technology
                    </a>
                    <a href="/category/business"
                        class="text-gray-700 dark:text-gray-300 hover:text-blue-600 dark:hover:text-blue-400 transition-colors">
                        Business
                    </a>
                </nav>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="min-h-screen">